# Open Issues

## April 26, 2023 update

* Everything broken in the Aug 13, 2022 update is still broken.
* flextable cross-refs and captions are still not working in Word output
* The flextable 0.9.1 CRAN release broke PDF output in Quarto books. Known problem and fixed in the development version on GitHub (0.9.2) `devtools::install_github("davidgohel/flextable")`
* gt (v0.9.0) cross-refs still broken in Word

## Aug 13, 2022 update

I have mostly figured out workarounds for the table package issues. The remaining big issues are

* For HTML, if you have two chapters (h1 level) in a single qmd it totally messes up the TOC. Word and PDF converters seem to figure it out ok and number things correctly.
    - I posted an issue https://github.com/quarto-dev/quarto-cli/issues/1712
    - This is important because we often don't know how many appendix chapters we will need. These are dynamically created based on the data. There is no good way to know this ahead of time. These report templates are used across very different regions and each region has a different number of appendices based on the number of, say, species or cities or whatever, in the region.
* When I have appendices so `appendices: ` in my YAML, the HTML TOC is messed up.
    - see https://rverse-tutorials.github.io/QmdReport/ and look at TOC
    - why doesn't the HTML figure out that the appendix A title is CRchum.csv?? Word and PDF figure that out.
* When I have `appendices: `, the PDF TOC and levels look right, but if I click on "Appendices" in the TOC, I go to References.
    - Look here to see what I mean [PDF version]( https://rverse-tutorials.github.io/QmdReport/A-Quarto-Template-Repo-to-Create-Big-Reports-and-Very-Long-Title-Because-Long-Titles-are-Common.pdf)
    - I would like to be able to have a `appendices.qmd` that I would go to. Maybe I can. I haven't tried.
* No merge and knit option. :( so no memory across chapters. That is a "feature" in many cases but some report writers use memory across chapters heavily.

## Aug 11, 2022 update

* flextable cross-refs don't work in pdf but kableExtra tables work and look better in some ways. So I use kableExtra for pdf's.
* flextable is best for Word but cross-refs are broken. The Quarto dev team knows about the problem.
* The Quarto {{include filename}} option for including files seems very limited or I don't know how to use it (most definitely true). The file has to be in same folder as the qmd that calls it.
* The Quarto {{include filename}} breaks if the thing you call is calling `knit_expand()`. Why? So weird. I might be doing something wrong.
* No merge and knit option. :( no sharing of variables across chapters
* Can't have two chapters (h1 level) in a single qmd so can't dynamically create chapters (one qmd with many h1 levels where that qmd is created dynamically)
* {gt} package and PDF table numbering don't mix! Breaks all numbering after a single `gt()` call. *Update. Fixed in the new gt update*

## Citation {.unnumbered}

EE Holmes, 2022. Quarto Report Template. Northwest Fisheries Science Center.


```{=openxml}
<w:p><w:r><w:br w:type="page"/></w:r></w:p>
```
